name: Build with Maven

on:
  push:
    branches: [ main ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 11, 17 ]

    name: Java ${{ matrix.java }}

    steps:
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v4

      - name: Step 2 - Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Step 3 - Build and verify with Maven
        run: mvn -B verify -DperformRelease=false -DskipNativeTests=true
